import type {
  Building,
  Contribution,
  Expense,
  Program,
  Performance,
  GalleryAlbum,
  GalleryImage,
  Sponsor,
  Volunteer,
  Task,
  EventInfo,
  MahaPrasadRSVP,
} from '../types';
import { DEFAULT_EVENT_ID } from '../firebase/collections';

export const INITIAL_EVENT_INFO: EventInfo = {
  id: DEFAULT_EVENT_ID,
  title: 'MAJESTIQUE EURISKA',
  subtitle: 'Cultural & Festive Calendar 2026–27',
  startDate: '2026-09-14',
  endDate: '2027-03-22',
  venue: 'Club house, Main Podium & Society Grounds',
  city: 'Pune, Maharashtra',
  tagline: 'Celebrating Togetherness All Year Round',
  heroBannerUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
  totalTarget: 347503,
  expectedPerFlat: 1500,
  buildingsCount: 3,
  totalFlats: 231,
};

export const INITIAL_BUILDINGS: Building[] = [
  {
    buildingId: 'A',
    name: 'A Building',
    totalFlats: 87,
    expectedPerFlat: 1500,
    targetAmount: 131000,
    collectedAmount: 77000,
    pendingAmount: 54000,
    paidFlatsCount: 51,
    pendingFlatsCount: 36,
  },
  {
    buildingId: 'B',
    name: 'B Building',
    totalFlats: 96,
    expectedPerFlat: 1500,
    targetAmount: 144502,
    collectedAmount: 72502,
    pendingAmount: 72000,
    paidFlatsCount: 48,
    pendingFlatsCount: 48,
  },
  {
    buildingId: 'C',
    name: 'C Building',
    totalFlats: 48,
    expectedPerFlat: 1500,
    targetAmount: 72001,
    collectedAmount: 45001,
    pendingAmount: 27000,
    paidFlatsCount: 30,
    pendingFlatsCount: 18,
  },
];

// Exact Real Residents for A Building (87 Flats + Refuge)
export const REAL_A_BUILDING_RESIDENTS = [
  { flat: '101', name: 'Mr. Yogesh Puri', amount: 0, status: 'PENDING' as const },
  { flat: '102', name: 'Mr. Arpit Atmaram Humane', amount: 0, status: 'PENDING' as const },
  { flat: '103', name: 'Mr. Dwarka Sharma', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '104', name: 'Mr. Ashish Tilakraj Jangda', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '105', name: 'Mr. Pranav Anil Kamble', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '106', name: 'Mrs. Shehnaaz Mohsin khan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '107', name: 'Mrs. Alefiya Aboozar Patrawala', amount: 0, status: 'PENDING' as const },
  { flat: '108', name: 'Mrs. Alefiya Aboozar Patrawala', amount: 0, status: 'PENDING' as const },
  { flat: '201', name: 'Mr. Parag Suresh Gaikwad', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '202', name: 'Mr. Anirudha C. Kshirsagar', amount: 0, status: 'PENDING' as const },
  { flat: '203', name: 'Mr. Maqsood Abdul Salam Baza', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '204', name: 'Mr. Sandeep Harbansalal Goyal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '205', name: 'Mr. Suryakiran M. Yedvilli', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '206', name: 'Mr. Pushpraj C. Kshirsagar', amount: 0, status: 'PENDING' as const },
  { flat: '207', name: 'Mr. Jitin Joglekar', amount: 0, status: 'PENDING' as const },
  { flat: '208', name: 'Mr. Mohammed A Khan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '301', name: 'Mr. Sandeep Kumar Mohanty', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '302', name: 'Bennett, Coleman & Co. Ltd.', amount: 0, status: 'PENDING' as const },
  { flat: '303', name: 'Mrs. Dipali Sandesh Parekh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '304', name: 'Mr. Manish K', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '305', name: 'Mr. Sanjay Kumar Roy Chowdhary', amount: 0, status: 'PENDING' as const },
  { flat: '306', name: 'Mr. Ajay Shrimali', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '307', name: 'Mr. Qazi Munwwar Ali Mumtaz Ali', amount: 0, status: 'PENDING' as const },
  { flat: '308', name: 'Mrs. Ankita Sinha', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '401', name: 'MR. Anil Singh Bisht', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '402', name: 'Mr. Sunny Garg', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '403', name: 'Mr. Azim Haghighi', amount: 0, status: 'PENDING' as const },
  { flat: '404', name: 'Mr. Galib & Mrs. Afroza Parkar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '405', name: 'Mudasir Alzahib', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '406', name: 'Mr. Surykan Nagnath Suryawanshi', amount: 0, status: 'PENDING' as const },
  { flat: '407', name: 'Mr. Kiran Kumar C.M.', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '408', name: 'Mrs. Salehi Shehnaz', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '501', name: 'Mrs. Vidya Praksh Dhiwar', amount: 0, status: 'PENDING' as const },
  { flat: '502', name: 'Shahnaz Shoukatali Dhamnekar', amount: 0, status: 'PENDING' as const },
  { flat: '503', name: 'Mr. Javed S', amount: 0, status: 'PENDING' as const },
  { flat: '504', name: 'Mrs. Mizba Mohd Saeed Shaikh', amount: 0, status: 'PENDING' as const },
  { flat: '505', name: 'Mr. Prashant S. Mahindrakar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '506', name: 'Mr. Edwin Anthony Joseph', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '507', name: 'Mr. Somnath Annappa Salunke', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '508', name: 'Mr. Ankesh Pratap', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '601', name: 'Mrs. Rama Kanta Sharma', amount: 0, status: 'PENDING' as const },
  { flat: '602', name: 'Mr. Himansu Sekhar Behera', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '603', name: 'Mr. Fakiruddin Alli Ahamed Khan', amount: 0, status: 'PENDING' as const },
  { flat: '604', name: 'Mr. Sayed Murtaza Sayed Reza Ajdar', amount: 0, status: 'PENDING' as const },
  { flat: '605', name: 'Ms. Riddhi Mankar', amount: 0, status: 'PENDING' as const },
  { flat: '606', name: 'Mr. Kalpesh Naraynrao Banai', amount: 0, status: 'PENDING' as const },
  { flat: '607', name: 'Mr. AshuKumar Harshwardhan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '608', name: 'Jannat Damji', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '701', name: 'Mr. Kumar Raj & Mrs. Soni Kumari', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '702', name: 'Mr. Nikhil Ramakant Kerkar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '703', name: 'Mr. Sandeep Kumar', amount: 0, status: 'PENDING' as const },
  { flat: '704', name: 'Mr. Sachin Nivrutti Savakhande', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '705', name: 'Mr. Ram Kumar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '707', name: 'Mr. Narayan Pandurang Dange', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '708', name: 'Mr. Wasim Jamal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '801', name: 'Mr. Sanchet J. Shetty', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '802', name: 'Mr. Suchit Prakash Gangreddiwar', amount: 0, status: 'PENDING' as const },
  { flat: '803', name: 'Ms. Patricia Robert Daniel', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '804', name: 'Mr. Aliakbar Abbas Haghighi', amount: 0, status: 'PENDING' as const },
  { flat: '805', name: 'Mr. Prasad Surya Yadavilli', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '806', name: 'Mr. Rushikesh Deepak Shinde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '807', name: 'Mr. Gaurav Pandey', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '808', name: 'Mrs. Sujata Surendra Hatkar', amount: 0, status: 'PENDING' as const },
  { flat: '901', name: 'Mr. Girish Jitendra Vij', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '902', name: 'Mr. Nikhil Bhosale', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '903', name: 'Mr. Dhanesh Unnithan & Mrs. Surya Kurup', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '904', name: 'Bennett, Coleman & Co. Ltd.', amount: 0, status: 'PENDING' as const },
  { flat: '905', name: 'Mr. Siddhesh Ghoting', amount: 0, status: 'PENDING' as const },
  { flat: '906', name: 'Mr. Mandar Sunil Govalkar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '907', name: 'Ms. Madhurima', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '908', name: 'Miss. Sakina Fatawala', amount: 0, status: 'PENDING' as const },
  { flat: '1001', name: 'Mr. Ashish', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1002', name: 'Bennett, Coleman & Co. Ltd.', amount: 0, status: 'PENDING' as const },
  { flat: '1003', name: 'Mrs. Shabnam Mirkar', amount: 0, status: 'PENDING' as const },
  { flat: '1004', name: 'Mr. Jagtap Sachin Ashok', amount: 0, status: 'PENDING' as const },
  { flat: '1005', name: 'Mr. Vinay Kumar Gupta', amount: 0, status: 'PENDING' as const },
  { flat: '1006', name: 'Raunak Jagdish Uderani', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1007', name: 'Mr. Amit Singh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1008', name: 'Ms Shilpa Tapiloo', amount: 0, status: 'PENDING' as const },
  { flat: '1101', name: 'Mr. Cedric', amount: 0, status: 'PENDING' as const },
  { flat: '1102', name: 'Mrs. Swati V. Dangde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1103', name: 'Mrs. Shubhada Ashok Gophane', amount: 2000, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1104', name: 'Mr. Shabbir Patrawala', amount: 0, status: 'PENDING' as const },
  { flat: '1105', name: 'Mrs. Deepjyoti Jaryal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1106', name: 'Ansari Farid Abdul Mannan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1107', name: 'Mr. Alfred Suresh O\'Neill', amount: 0, status: 'PENDING' as const },
  { flat: '1108', name: 'Mr. Kiran Ramdas Tajane', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
];

// Exact Real Residents for B Building (96 Flats: Floors 1 to 12)
export const REAL_B_BUILDING_RESIDENTS = [
  // Floor 1
  { flat: '101', name: 'Mr. Naik Preetam Premanand', amount: 0, status: 'PENDING' as const },
  { flat: '102', name: 'Mr. Vikram Kumar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '103', name: 'Mr. Rajeev Pawar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '104', name: 'Mrs. Sachdev Veena Harish', amount: 0, status: 'PENDING' as const },
  { flat: '105', name: 'Mrs. Joshna V. Nile & Mr. Vaibhav Nile', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '106', name: 'Mrs. Sharma Bhavna', amount: 0, status: 'PENDING' as const },
  { flat: '107', name: 'Mr. Javed Shaikh', amount: 2000, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '108', name: 'Mrs. Belinda sahil Bhatia', amount: 0, status: 'PENDING' as const },

  // Floor 2
  { flat: '201', name: 'Lalita S', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '202', name: 'Mrs. Abrar Sayed', amount: 0, status: 'PENDING' as const },
  { flat: '203', name: 'Ms. Priyanka', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '204', name: 'Mr. Sudhir Shrivastava', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '205', name: 'Mr. Shahebaz Mainuddin Shaikh', amount: 0, status: 'PENDING' as const },
  { flat: '206', name: 'Mr. Krishna Kumar Verma', amount: 0, status: 'PENDING' as const },
  { flat: '207', name: 'Mr. Sahil Monga & Nisha Kumari', amount: 0, status: 'PENDING' as const },
  { flat: '208', name: 'Mr. Sambhaji Jadav', amount: 0, status: 'PENDING' as const },

  // Floor 3
  { flat: '301', name: 'Miss. Deepa Thakur Rao', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '302', name: 'Mr. Russell Nayak', amount: 0, status: 'PENDING' as const },
  { flat: '303', name: 'Mr. Ankush Bobade', amount: 0, status: 'PENDING' as const },
  { flat: '304', name: 'Mr. Saurabh Jaiswal', amount: 0, status: 'PENDING' as const },
  { flat: '305', name: 'Mrs. Neha Ashton Lazarus', amount: 0, status: 'PENDING' as const },
  { flat: '306', name: 'Mr. Abhishek Jeevan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '307', name: 'Mr. Sunil Kumar & Abha Kumar(Rahul Singh)', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '308', name: 'Mr. Moses Mascarenhas', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 4
  { flat: '401', name: 'Mr. Shahebaz Mainuddin Shaikh', amount: 0, status: 'PENDING' as const },
  { flat: '402', name: 'Mr. Vishal Dilipkumar Shende', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '403', name: 'Miss. Anjali Ajgaonkar', amount: 0, status: 'PENDING' as const },
  { flat: '404', name: 'Ms. Maya Ghughe / Pratibha Malik', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '405', name: 'Mr. Santosh shinde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '406', name: 'Mr. Shailesh Namekar', amount: 0, status: 'PENDING' as const },
  { flat: '407', name: 'Mr. Gaurav Pandey', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '408', name: 'Mrs. Gunjandevi Yadav & Mithlesh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 5
  { flat: '501', name: 'Mrs. Arpita Bhattachrjee', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '502', name: 'Ms. Swarna Biswas', amount: 0, status: 'PENDING' as const },
  { flat: '503', name: 'Mr. Vijaya Udhavrao Kolpe', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '504', name: 'Mr. Parag Bujone', amount: 0, status: 'PENDING' as const },
  { flat: '505', name: 'Amoy Ahwah Lee', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '506', name: 'Mr. Shyam Sunder', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '507', name: 'Mr. Digambar Tanaji Giribuwa', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '508', name: 'Mr. Pradeep Dattajirao Desai', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 6
  { flat: '601', name: 'Mrs. Madhu Kaushik', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '602', name: 'Mr. Apurv', amount: 0, status: 'PENDING' as const },
  { flat: '603', name: 'Mr. Jude joseph Dsouza', amount: 0, status: 'PENDING' as const },
  { flat: '604', name: 'Mr. Prabhat Singh & Mallika Singh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '605', name: 'Mr. Hansmukh Morarji', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '606', name: 'Mrs. Anju Gupta', amount: 1501, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '607', name: 'Mr. Rohan Uday Kavde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '608', name: 'Mr. Sambhaji Jadav', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 7
  { flat: '701', name: 'Mrs. Samina Sajid Malik', amount: 0, status: 'PENDING' as const },
  { flat: '702', name: 'Ms. Priyanka patil', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '703', name: 'Mr. Rohit Prachure', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '704', name: 'Ms. Aarti Dalvi', amount: 0, status: 'PENDING' as const },
  { flat: '705', name: 'Mr. Anand Rakesh Tamang', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '706', name: 'Mrs. Tejshree Deshmukh', amount: 0, status: 'PENDING' as const },
  { flat: '707', name: 'Mr. Deepak Dharmaraj', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '708', name: 'Mr. Manish Ranjan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 8
  { flat: '801', name: 'Mr. Shubham Kumar Singh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '802', name: 'Mr. Sachin Singh & Rajbala Devi', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '803', name: 'Mr. Satish Shivram Bhosale', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '804', name: 'Mr. Moin Munir Shaikh Nuzhat', amount: 0, status: 'PENDING' as const },
  { flat: '805', name: 'Mr. Imran Deshmukh', amount: 0, status: 'PENDING' as const },
  { flat: '806', name: 'Mr. Ankush Ramrao Shinde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '807', name: 'Mr. Ludhani', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '808', name: 'Mr. Mohit', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 9
  { flat: '901', name: 'Mr. Ganesh Jagannath Jagtap', amount: 0, status: 'PENDING' as const },
  { flat: '902', name: 'Mrs. Suprabha Nandi', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '903', name: 'Mrs. Seema Manoj Pallod', amount: 0, status: 'PENDING' as const },
  { flat: '904', name: 'Mr. Amar Wale', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '905', name: 'Mr. Yusuf Ampanwala', amount: 0, status: 'PENDING' as const },
  { flat: '906', name: 'Mr. Rajesh Bapusaheb Khude', amount: 0, status: 'PENDING' as const },
  { flat: '907', name: 'Mr. Atul Ashok Jagtap', amount: 0, status: 'PENDING' as const },
  { flat: '908', name: 'Mrs. Ekta Gaikwad', amount: 0, status: 'PENDING' as const },

  // Floor 10
  { flat: '1001', name: 'Glyniis Aubey', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1002', name: 'Mr. Ramraje Kakde', amount: 0, status: 'PENDING' as const },
  { flat: '1003', name: 'Mrs. Sampada Mohan Nagraj', amount: 0, status: 'PENDING' as const },
  { flat: '1004', name: 'Miss. Rashida Madraswala', amount: 0, status: 'PENDING' as const },
  { flat: '1005', name: 'Mr. Surendra Dubey', amount: 0, status: 'PENDING' as const },
  { flat: '1006', name: 'Mrs. Alka Dubey', amount: 1501, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1007', name: 'Mr. Mayur Vilasrao Jagtap', amount: 0, status: 'PENDING' as const },
  { flat: '1008', name: 'Mr. Rajiv Arora', amount: 0, status: 'PENDING' as const },

  // Floor 11
  { flat: '1101', name: 'Mr. Aryan Pandey', amount: 0, status: 'PENDING' as const },
  { flat: '1102', name: 'Agnelo Norman', amount: 0, status: 'PENDING' as const },
  { flat: '1103', name: 'Mr. Ravindra Dixit & Swagata Dixit', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1104', name: 'Mrs. Sweta Prasad', amount: 0, status: 'PENDING' as const },
  { flat: '1105', name: 'Mr. Hussain', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1106', name: 'Mr. Ramesh Solanki', amount: 0, status: 'PENDING' as const },
  { flat: '1107', name: 'Mrs. Nivedita Maheshwari', amount: 0, status: 'PENDING' as const },
  { flat: '1108', name: 'Mr. Sanjit Shenoy', amount: 0, status: 'PENDING' as const },

  // Floor 12
  { flat: '1201', name: 'Mrs. Priyanka Shah', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1202', name: 'Mr. Deepak Nagdev', amount: 0, status: 'PENDING' as const },
  { flat: '1203', name: 'Mrs. Samina Lokhandwala', amount: 0, status: 'PENDING' as const },
  { flat: '1204', name: 'Mrs. Tina Arun Rohra', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1205', name: 'Mr. Manoj Madhavdas Lakhi', amount: 0, status: 'PENDING' as const },
  { flat: '1206', name: 'Mr. Rayan Barretto', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1207', name: 'Mr. Rajan Duggal & Monika Sharma', amount: 0, status: 'PENDING' as const },
  { flat: '1208', name: 'Mr. Rishabh kumar', amount: 0, status: 'PENDING' as const },
];



// Exact Real Residents for C Building (48 Flats: Floors 1 to 6)
export const REAL_C_BUILDING_RESIDENTS = [
  // Floor 1
  { flat: '101', name: 'Clinton Fernandes', amount: 0, status: 'PENDING' as const },
  { flat: '102', name: 'Dhanraj Mane', amount: 0, status: 'PENDING' as const },
  { flat: '103', name: 'Samrat Choudhury', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '104', name: 'Saud Shaikh', amount: 0, status: 'PENDING' as const },
  { flat: '105', name: 'Raheal Rathod', amount: 0, status: 'PENDING' as const },
  { flat: '106', name: 'Ms. Veronica Francis', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '107', name: 'Sanmay Jagtap', amount: 0, status: 'PENDING' as const },
  { flat: '108', name: 'Yogita Shirdhankar', amount: 0, status: 'PENDING' as const },

  // Floor 2
  { flat: '201', name: 'Imrankhan Pathan', amount: 0, status: 'PENDING' as const },
  { flat: '202', name: 'Ashley Carrasco', amount: 0, status: 'PENDING' as const },
  { flat: '203', name: 'Garima Rana', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '204', name: 'Sufiyan Tamboli', amount: 0, status: 'PENDING' as const },
  { flat: '205', name: 'Chetan Habib', amount: 0, status: 'PENDING' as const },
  { flat: '206', name: 'Shriniketan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '207', name: 'Nishad Mohandas', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '208', name: 'Madhu Verma', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 3
  { flat: '301', name: 'Sameer Kaulagekar', amount: 0, status: 'PENDING' as const },
  { flat: '302', name: 'Amol Sathe', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '303', name: 'Sunil Agrawal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '304', name: 'Nitesh A', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '305', name: 'Abid S', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '306', name: 'Mr. Rohan Kotkar', amount: 0, status: 'PENDING' as const },
  { flat: '307', name: 'Rajesh Sapkal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '308', name: 'Aamay Arora', amount: 0, status: 'PENDING' as const },

  // Floor 4
  { flat: '401', name: 'Kaustubh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '402', name: 'Rohan Veer', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '403', name: 'Anosh', amount: 0, status: 'PENDING' as const },
  { flat: '404', name: 'Sameer Perampalli', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '405', name: 'Rahul Khade', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '406', name: 'Noel Paul', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '407', name: 'Parikshit Dharmale', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '408', name: 'Aniket', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 5
  { flat: '501', name: 'Anirudh Dipak Fulzele', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '502', name: 'Sandhya Gaikwad', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '503', name: 'Rachel', amount: 0, status: 'PENDING' as const },
  { flat: '504', name: 'Santanu Gauratra', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '505', name: 'Vivek Chavan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '506', name: 'Hussain', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '507', name: 'Satish Shetty', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '508', name: 'Surajit Das', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 6
  { flat: '601', name: 'Amber', amount: 0, status: 'PENDING' as const },
  { flat: '602', name: 'Naveen Gupta', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '603', name: 'Param N', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '604', name: 'Hasina S', amount: 0, status: 'PENDING' as const },
  { flat: '605', name: 'Tasneem Palodawala', amount: 0, status: 'PENDING' as const },
  { flat: '606', name: 'Vivek Rahate', amount: 1501, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '607', name: 'Husham', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '608', name: 'Amal Nair', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
];

export function generateSeedContributions(): Contribution[] {
  const contributions: Contribution[] = [];
  let idCounter = 100;

  // 1. Insert real A Building residents (87 flats)
  REAL_A_BUILDING_RESIDENTS.forEach((item, idx) => {
    idCounter++;
    const isPaid = item.status === 'PAID';
    const expected = 1500;
    const day = (idx % 14) + 15;

    contributions.push({
      id: `contrib-A-${item.flat}`,
      eventId: DEFAULT_EVENT_ID,
      buildingId: 'A',
      flatNumber: `A-${item.flat}`,
      residentName: item.name,
      expectedAmount: expected,
      paidAmount: isPaid ? item.amount : 0,
      paymentMode: item.mode,
      transactionId: isPaid ? `UPI-${Math.floor(10000000 + (idx + 1) * 987654)}` : undefined,
      receiptNumber: isPaid ? `REC-2026-A${item.flat}` : undefined,
      paymentDate: isPaid ? `2026-08-${day < 10 ? '0' + day : day}` : undefined,
      status: item.status,
      remarks: isPaid ? 'Payment received online' : 'Pending follow-up',
      createdAt: '2026-08-01T10:00:00Z',
      updatedAt: '2026-08-30T18:00:00Z',
    });
  });

  // 2. Insert real B Building residents (96 flats)
  REAL_B_BUILDING_RESIDENTS.forEach((item, idx) => {
    idCounter++;
    const isPaid = item.status === 'PAID';
    const expected = 1500;
    const day = (idx % 14) + 15;

    contributions.push({
      id: `contrib-B-${item.flat}`,
      eventId: DEFAULT_EVENT_ID,
      buildingId: 'B',
      flatNumber: `B-${item.flat}`,
      residentName: item.name,
      expectedAmount: expected,
      paidAmount: isPaid ? item.amount : 0,
      paymentMode: item.mode,
      transactionId: isPaid ? `UPI-${Math.floor(20000000 + (idx + 1) * 876543)}` : undefined,
      receiptNumber: isPaid ? `REC-2026-B${item.flat}` : undefined,
      paymentDate: isPaid ? `2026-08-${day < 10 ? '0' + day : day}` : undefined,
      status: item.status,
      remarks: isPaid ? 'Payment received online' : 'Pending follow-up',
      createdAt: '2026-08-01T10:00:00Z',
      updatedAt: '2026-08-30T18:00:00Z',
    });
  });

  // 3. Insert real C Building residents (48 flats)
  REAL_C_BUILDING_RESIDENTS.forEach((item, idx) => {
    idCounter++;
    const isPaid = item.status === 'PAID';
    const expected = 1500;
    const day = (idx % 14) + 15;

    contributions.push({
      id: `contrib-C-${item.flat}`,
      eventId: DEFAULT_EVENT_ID,
      buildingId: 'C',
      flatNumber: `C-${item.flat}`,
      residentName: item.name,
      expectedAmount: expected,
      paidAmount: isPaid ? item.amount : 0,
      paymentMode: item.mode,
      transactionId: isPaid ? `UPI-${Math.floor(30000000 + (idx + 1) * 765432)}` : undefined,
      receiptNumber: isPaid ? `REC-2026-C${item.flat}` : undefined,
      paymentDate: isPaid ? `2026-08-${day < 10 ? '0' + day : day}` : undefined,
      status: item.status,
      remarks: isPaid ? 'Payment received online' : 'Pending follow-up',
      createdAt: '2026-08-01T10:00:00Z',
      updatedAt: '2026-08-30T18:00:00Z',
    });
  });

  return contributions;
}

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: 'prog-1',
    eventId: DEFAULT_EVENT_ID,
    title: 'Shri Ganesh Aagman',
    date: '2026-09-14',
    time: '05:00 PM',
    stage: 'Main Entrance & Club House',
    category: 'Ceremony',
    description: 'Grand Shri Ganesh Aagman procession with traditional Dhol Tasha beats and welcome ceremony starting at 5:00 PM onwards.',
    durationMinutes: 180,
    performers: ['Managing Committee', 'Priest Shastri Ji', 'Euriska Dhol Tasha Pathak'],
    order: 1,
    isToday: false,
  },
  {
    id: 'prog-aarti',
    eventId: DEFAULT_EVENT_ID,
    title: 'Daily Aarti (Morning & Evening)',
    date: '2026-09-14',
    time: '09:00 AM & 08:00 PM',
    stage: 'Club House Podium',
    category: 'Ceremony',
    description: 'Daily Aarti Timings (14 Sep – 25 Sep): Morning Aarti at 9:00 AM and Evening Aarti at 8:00 PM followed by Modak Prasad distribution.',
    durationMinutes: 45,
    performers: ['All Society Families & Prasad Seva Hosts'],
    order: 2,
    isToday: false,
  },
  {
    id: 'prog-2',
    eventId: DEFAULT_EVENT_ID,
    title: 'Carnival – Drawing Competition',
    date: '2026-09-19',
    time: '03:00 PM',
    stage: 'Amphitheatre & Clubhouse',
    category: 'Games',
    description: 'Carnival special Kids & Youth Drawing Competition from 3:00 PM to 5:00 PM. Art materials provided.',
    durationMinutes: 120,
    performers: ['Euriska Little Stars & Young Artists'],
    order: 3,
    isToday: false,
  },
  {
    id: 'prog-3',
    eventId: DEFAULT_EVENT_ID,
    title: 'Carnival – City cha Bappa with Radio City 91.1 FM',
    date: '2026-09-19',
    time: '06:00 PM',
    stage: 'Grand Main Stage',
    category: 'Music',
    description: "Carnival Live Entertainment: 'City cha Bappa' on-ground event with Radio City 91.1 FM team starting at 6:00 PM onwards!",
    durationMinutes: 120,
    performers: ['Radio City 91.1 FM RJ & Team', 'Euriska Residents'],
    order: 4,
    isToday: false,
  },
  {
    id: 'prog-4',
    eventId: DEFAULT_EVENT_ID,
    title: 'Carnival – Food Stalls',
    date: '2026-09-19',
    time: '07:00 PM',
    stage: 'Society Lawn & Food Zone',
    category: 'Feast',
    description: 'Festive Food Stalls serving mouth-watering delicacies, chaats, live counters, and treats starting from 7:00 PM onwards.',
    durationMinutes: 180,
    performers: ['Food Stalls & Resident Culinary Enthusiasts'],
    order: 5,
    isToday: false,
  },
  {
    id: 'prog-5',
    eventId: DEFAULT_EVENT_ID,
    title: 'Kalakriti – Talent Show ("Your Talent Our Stage!")',
    date: '2026-09-20',
    time: '06:00 PM',
    stage: 'Grand Main Stage',
    category: 'Dance',
    description: 'Kalakriti Talent Show ("Your Talent Our Stage!"): Spectacular evening of dance, singing, music, drama, and cultural showcase starting at 6:00 PM onwards.',
    durationMinutes: 180,
    performers: ['Euriska Cultural Performers', 'Euriska Talent Troupe'],
    order: 6,
    isToday: false,
  },
  {
    id: 'prog-6',
    eventId: DEFAULT_EVENT_ID,
    title: 'Shri Satyanarayan Katha',
    date: '2026-09-24',
    time: '04:00 PM',
    stage: 'Club House Podium',
    category: 'Ceremony',
    description: 'Auspicious Shri Satyanarayan Pooja & Katha recitation with sacred rituals for society prosperity starting at 4:00 PM onwards.',
    durationMinutes: 180,
    performers: ['Priest Shastri Ji', 'All Society Devotees & Families'],
    order: 7,
    isToday: false,
  },
  {
    id: 'prog-7',
    eventId: DEFAULT_EVENT_ID,
    title: 'Mahaprasad (Dinner)',
    date: '2026-09-24',
    time: '08:00 PM',
    stage: 'Clubhouse Lawn & Dining Area',
    category: 'Feast',
    description: 'Grand Community Mahaprasad Dinner for all Euriska residents, devotees, and guests starting from 8:00 PM onwards.',
    durationMinutes: 180,
    performers: ['Euriska Cultural Committee Volunteers', 'Royal Caterers'],
    order: 8,
    isToday: false,
  },
  {
    id: 'prog-8',
    eventId: DEFAULT_EVENT_ID,
    title: 'Shri Ganesh Visarjan',
    date: '2026-09-25',
    time: '04:00 PM',
    stage: 'Main Ground & Visarjan Route',
    category: 'Ceremony',
    description: 'Grand Anant Chaturdashi Ganesh Visarjan procession with Gulal, Lezim, Dhol Tasha beats, and emotional farewell starting at 4:00 PM onwards.',
    durationMinutes: 240,
    performers: ['Entire Euriska Society Community', 'Dhol Tasha Troupe'],
    order: 9,
    isToday: false,
  },
  // Festival Calendar 2026-2027
  {
    id: 'festival-1',
    eventId: DEFAULT_EVENT_ID,
    title: 'Sharad Navratri 2026 - Begins',
    date: '2026-10-11',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Sharad Navratri festival begins. A 9-day celebration honoring the divine feminine energy. Vijayadashami (Dussehra) concludes the festival on October 20.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 10,
  },
  {
    id: 'festival-2',
    eventId: DEFAULT_EVENT_ID,
    title: 'Vijayadashami (Dussehra) 2026',
    date: '2026-10-20',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Concludes the 9-day Sharad Navratri celebration. Vijayadashami marks the victory of good over evil and the triumph of Lord Rama over Ravana.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 11,
  },
  {
    id: 'festival-3',
    eventId: DEFAULT_EVENT_ID,
    title: 'Diwali 2026 - Festival of Lights',
    date: '2026-11-08',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Diwali 2026 - The festival of lights celebrating the victory of light over darkness and good over evil. A time for family gatherings, celebrations, and joy.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 12,
  },
  {
    id: 'festival-4',
    eventId: DEFAULT_EVENT_ID,
    title: 'Holi 2027 - Festival of Colors',
    date: '2027-03-22',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Holi 2027 - The festival of colors celebrating spring and new beginnings. Holika Dahan, the bonfire ritual, takes place on March 21, 2027.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 13,
  },
  {
    id: 'festival-5',
    eventId: DEFAULT_EVENT_ID,
    title: 'Holika Dahan 2027',
    date: '2027-03-21',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Holika Dahan - Traditional bonfire ritual marking the eve of Holi. A symbolic representation of burning evil and purification.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 14,
  },
  {
    id: 'festival-6',
    eventId: DEFAULT_EVENT_ID,
    title: 'Eid al-Fitr 2027',
    date: '2027-03-10',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Eid al-Fitr 2027 - The festival marking the end of Ramadan. A day of celebration, feasting, and community gatherings with joy and blessings.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 15,
  },
];

export const INITIAL_PERFORMANCES: Performance[] = [];

export const INITIAL_ALBUMS: GalleryAlbum[] = [];

export const INITIAL_GALLERY_IMAGES: GalleryImage[] = [];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-dhol-pathak-01',
    eventId: DEFAULT_EVENT_ID,
    category: 'Ganesh Chaturthi' as any,
    vendor: 'Dhol Pathak',
    description: 'Adv booking',
    amount: 5000,
    paymentMode: 'ONLINE',
    status: 'APPROVED',
    expenseDate: '2026-09-01',
    invoiceNumber: 'ADV-DP-2026-01',
    createdBy: 'Sachin Singh',
    paidBy: 'Sachin Singh',
    approvedBy: 'Sachin Singh',
    approvedAt: '2026-09-01T10:00:00Z',
    remarks: 'Adv booking for Ganesh Chaturthi',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
];

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: 'spon-rahul-murti-b307',
    eventId: DEFAULT_EVENT_ID,
    name: 'Rahul',
    tier: 'Platinum',
    amount: 0,
    logoUrl: '/ganesh_murti_sponsor.jpg',
    paymentStatus: 'PAID',
    contactPerson: 'Rahul',
    contactPhone: '+91 98230 00307',
    flatNumber: 'B-307',
    buildingId: 'B',
    sevaType: 'Murti',
    sevaCategory: 'Shri Ganesh Murti Seva',
    description: 'Devotee sponsor for Sacred Shri Ganesh Murti (Idol) Seva for Euriska 2026',
  },
  {
    id: 'spon-prashant-decor-a505',
    eventId: DEFAULT_EVENT_ID,
    name: 'Prashant',
    tier: 'Gold',
    amount: 0,
    logoUrl: '/dagdusheth_decoration.jpg',
    paymentStatus: 'PAID',
    contactPerson: 'Prashant Mahindrakar',
    contactPhone: '+91 95909 44363',
    flatNumber: 'A-505',
    buildingId: 'A',
    sevaType: 'Decoration',
    sevaCategory: 'Mandap & Stage Decoration Seva',
    description: 'Devotee sponsor for Grand Stage & Mandap Floral Decoration Seva for Euriska 2026',
  },
  {
    id: 'spon-sachin-sunil-mahaprasad',
    eventId: DEFAULT_EVENT_ID,
    name: 'Sachin & Sunil',
    tier: 'Platinum',
    amount: 0,
    logoUrl: '/mahaprasad_sponsor.jpg',
    paymentStatus: 'PAID',
    contactPerson: 'Sachin Savakhande & Sunil Agrawal',
    contactPhone: '+91 99600 73627 / +91 90288 14503',
    flatNumber: 'A-704 & C-303',
    buildingId: 'A',
    sevaType: 'Maha Prasad',
    sevaCategory: 'Grand Maha Prasad Seva',
    description: 'Devotee sponsors for Grand Maha Prasad Community Feast (24th Sep) for Euriska 2026',
  },
  {
    id: 'spon-dwarka-almirah-a103',
    eventId: DEFAULT_EVENT_ID,
    name: 'Dwarka',
    tier: 'Gold',
    amount: 0,
    logoUrl: '/almirah_sponsor.jpg',
    paymentStatus: 'PAID',
    contactPerson: 'Dwarka Sharma',
    contactPhone: '+91 77989 85631',
    flatNumber: 'A-103',
    buildingId: 'A',
    sevaType: 'Almirah',
    sevaCategory: 'Temple & Mandap Almirah Seva',
    description: 'Devotee sponsor for Society Temple & Pooja Samagri Storage Almirah Seva for Euriska 2026',
  },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-1',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Dwarka Sharma',
    role: 'Cultural Committee Volunteer',
    buildingId: 'A',
    flatNumber: 'A-103',
    phone: '+91 77989 85631',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
  {
    id: 'vol-2',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Ganesh Jagtap',
    role: 'Cultural Committee Volunteer',
    buildingId: 'B',
    flatNumber: 'B-901',
    phone: '+91 98342 45224',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
  {
    id: 'vol-3',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Mandar Govalkar',
    role: 'Cultural Committee Volunteer',
    buildingId: 'A',
    flatNumber: 'A-906',
    phone: '+91 90963 05367',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
  {
    id: 'vol-4',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Prashant Mahindrakar',
    role: 'Cultural Committee Volunteer',
    buildingId: 'A',
    flatNumber: 'A-505',
    phone: '+91 95909 44363',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
  {
    id: 'vol-5',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Pravin Giribuwa',
    role: 'Cultural Committee Volunteer',
    buildingId: 'B',
    flatNumber: 'B-507',
    phone: '+91 98230 00507',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
  {
    id: 'vol-6',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Rahul Singh',
    role: 'Cultural Committee Volunteer',
    buildingId: 'B',
    flatNumber: 'B-307',
    phone: '+91 90282 05680',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
  {
    id: 'vol-7',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Sachin Savakhande',
    role: 'Cultural Committee Volunteer',
    buildingId: 'A',
    flatNumber: 'A-704',
    phone: '+91 99600 73627',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
  {
    id: 'vol-8',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Sachin Singh',
    role: 'Cultural Committee Volunteer',
    buildingId: 'B',
    flatNumber: 'B-801',
    phone: '+91 83904 57515',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
  {
    id: 'vol-9',
    eventId: DEFAULT_EVENT_ID,
    name: 'Mr. Sunil Agrawal',
    role: 'Cultural Committee Volunteer',
    buildingId: 'C',
    flatNumber: 'C-303',
    phone: '+91 90288 14503',
    shiftTime: 'Festival Days',
    status: 'AVAILABLE',
  },
];

export const INITIAL_TASKS: Task[] = [];

/**
 * Automatically enrolls all flats who paid the Rs. 1,500 contribution
 * with an initial headcount of 2 people per family (8:00 PM - 10:00 PM).
 */
export function generateSeedMahaPrasadRSVPs(): MahaPrasadRSVP[] {
  const rsvps: MahaPrasadRSVP[] = [];

  // 1. Wing A Paid Flats (2 people per family)
  REAL_A_BUILDING_RESIDENTS.filter((item) => item.status === 'PAID').forEach((item) => {
    rsvps.push({
      id: `rsvp-A-${item.flat}`,
      buildingId: 'A',
      flatNumber: `A-${item.flat}`,
      residentName: item.name,
      phone: '',
      adultsCount: 2,
      childrenCount: 0,
      totalHeadcount: 2,
      dietaryPreference: 'REGULAR',
      timeSlot: '8:00 PM - 9:00 PM',
      isVolunteering: false,
      notes: '',
      createdAt: '2026-08-20T10:00:00Z',
      updatedAt: '2026-08-20T10:00:00Z',
    });
  });

  // 2. Wing B Paid Flats (2 people per family)
  REAL_B_BUILDING_RESIDENTS.filter((item) => item.status === 'PAID').forEach((item) => {
    rsvps.push({
      id: `rsvp-B-${item.flat}`,
      buildingId: 'B',
      flatNumber: `B-${item.flat}`,
      residentName: item.name,
      phone: '',
      adultsCount: 2,
      childrenCount: 0,
      totalHeadcount: 2,
      dietaryPreference: 'REGULAR',
      timeSlot: '8:00 PM - 9:00 PM',
      isVolunteering: false,
      notes: '',
      createdAt: '2026-08-20T10:00:00Z',
      updatedAt: '2026-08-20T10:00:00Z',
    });
  });

  // 3. Wing C Paid Flats (2 people per family)
  REAL_C_BUILDING_RESIDENTS.filter((item) => item.status === 'PAID').forEach((item) => {
    rsvps.push({
      id: `rsvp-C-${item.flat}`,
      buildingId: 'C',
      flatNumber: `C-${item.flat}`,
      residentName: item.name,
      phone: '',
      adultsCount: 2,
      childrenCount: 0,
      totalHeadcount: 2,
      dietaryPreference: 'REGULAR',
      timeSlot: '8:00 PM - 9:00 PM',
      isVolunteering: false,
      notes: '',
      createdAt: '2026-08-20T10:00:00Z',
      updatedAt: '2026-08-20T10:00:00Z',
    });
  });

  return rsvps;
}

export const INITIAL_MAHA_PRASAD_RSVPS: MahaPrasadRSVP[] = generateSeedMahaPrasadRSVPs();

