import type {
  Building,
  Contribution,
  Expense,
  Program,
  Performance,
  GalleryAlbum,
  GalleryImage,
  Sponsor,
  Volunteer,
  Task,
  EventInfo,
  MahaPrasadRSVP,
} from '../types';
import { DEFAULT_EVENT_ID } from '../firebase/collections';

export const INITIAL_EVENT_INFO: EventInfo = {
  id: DEFAULT_EVENT_ID,
  title: 'MAJESTIQUE EURISKA',
  subtitle: 'Cultural & Festive Calendar 2026–27',
  startDate: '2026-09-14',
  endDate: '2027-03-22',
  venue: 'Club house, Main Podium & Society Grounds',
  city: 'Pune, Maharashtra',
  tagline: 'Celebrating Togetherness All Year Round',
  heroBannerUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
  totalTarget: 347503,
  expectedPerFlat: 1500,
  buildingsCount: 3,
  totalFlats: 231,
};

export const INITIAL_BUILDINGS: Building[] = [
  {
    buildingId: 'A',
    name: 'A Building',
    totalFlats: 87,
    expectedPerFlat: 1500,
    targetAmount: 131000,
    collectedAmount: 77000,
    pendingAmount: 54000,
    paidFlatsCount: 51,
    pendingFlatsCount: 36,
  },
  {
    buildingId: 'B',
    name: 'B Building',
    totalFlats: 96,
    expectedPerFlat: 1500,
    targetAmount: 144502,
    collectedAmount: 72502,
    pendingAmount: 72000,
    paidFlatsCount: 48,
    pendingFlatsCount: 48,
  },
  {
    buildingId: 'C',
    name: 'C Building',
    totalFlats: 48,
    expectedPerFlat: 1500,
    targetAmount: 72001,
    collectedAmount: 45001,
    pendingAmount: 27000,
    paidFlatsCount: 30,
    pendingFlatsCount: 18,
  },
];

// Exact Real Residents for A Building (87 Flats + Refuge)
export const REAL_A_BUILDING_RESIDENTS = [
  { flat: '101', name: 'Mr. Yogesh Puri', amount: 0, status: 'PENDING' as const },
  { flat: '102', name: 'Mr. Arpit Atmaram Humane', amount: 0, status: 'PENDING' as const },
  { flat: '103', name: 'Mr. Dwarka Sharma', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '104', name: 'Mr. Ashish Tilakraj Jangda', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '105', name: 'Mr. Pranav Anil Kamble', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '106', name: 'Mrs. Shehnaaz Mohsin khan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '107', name: 'Mrs. Alefiya Aboozar Patrawala', amount: 0, status: 'PENDING' as const },
  { flat: '108', name: 'Mrs. Alefiya Aboozar Patrawala', amount: 0, status: 'PENDING' as const },
  { flat: '201', name: 'Mr. Parag Suresh Gaikwad', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '202', name: 'Mr. Anirudha C. Kshirsagar', amount: 0, status: 'PENDING' as const },
  { flat: '203', name: 'Mr. Maqsood Abdul Salam Baza', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '204', name: 'Mr. Sandeep Harbansalal Goyal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '205', name: 'Mr. Suryakiran M. Yedvilli', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '206', name: 'Mr. Pushpraj C. Kshirsagar', amount: 0, status: 'PENDING' as const },
  { flat: '207', name: 'Mr. Jitin Joglekar', amount: 0, status: 'PENDING' as const },
  { flat: '208', name: 'Mr. Mohammed A Khan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '301', name: 'Mr. Sandeep Kumar Mohanty', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '302', name: 'Bennett, Coleman & Co. Ltd.', amount: 0, status: 'PENDING' as const },
  { flat: '303', name: 'Mrs. Dipali Sandesh Parekh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '304', name: 'Mr. Manish K', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '305', name: 'Mr. Sanjay Kumar Roy Chowdhary', amount: 0, status: 'PENDING' as const },
  { flat: '306', name: 'Mr. Ajay Shrimali', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '307', name: 'Mr. Qazi Munwwar Ali Mumtaz Ali', amount: 0, status: 'PENDING' as const },
  { flat: '308', name: 'Mrs. Ankita Sinha', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '401', name: 'MR. Anil Singh Bisht', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '402', name: 'Mr. Sunny Garg', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '403', name: 'Mr. Azim Haghighi', amount: 0, status: 'PENDING' as const },
  { flat: '404', name: 'Mr. Galib & Mrs. Afroza Parkar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '405', name: 'Mudasir Alzahib', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '406', name: 'Mr. Surykan Nagnath Suryawanshi', amount: 0, status: 'PENDING' as const },
  { flat: '407', name: 'Mr. Kiran Kumar C.M.', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '408', name: 'Mrs. Salehi Shehnaz', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '501', name: 'Mrs. Vidya Praksh Dhiwar', amount: 0, status: 'PENDING' as const },
  { flat: '502', name: 'Shahnaz Shoukatali Dhamnekar', amount: 0, status: 'PENDING' as const },
  { flat: '503', name: 'Mr. Javed S', amount: 0, status: 'PENDING' as const },
  { flat: '504', name: 'Mrs. Mizba Mohd Saeed Shaikh', amount: 0, status: 'PENDING' as const },
  { flat: '505', name: 'Mr. Prashant S. Mahindrakar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '506', name: 'Mr. Edwin Anthony Joseph', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '507', name: 'Mr. Somnath Annappa Salunke', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '508', name: 'Mr. Ankesh Pratap', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '601', name: 'Mrs. Rama Kanta Sharma', amount: 0, status: 'PENDING' as const },
  { flat: '602', name: 'Mr. Himansu Sekhar Behera', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '603', name: 'Mr. Fakiruddin Alli Ahamed Khan', amount: 0, status: 'PENDING' as const },
  { flat: '604', name: 'Mr. Sayed Murtaza Sayed Reza Ajdar', amount: 0, status: 'PENDING' as const },
  { flat: '605', name: 'Ms. Riddhi Mankar', amount: 0, status: 'PENDING' as const },
  { flat: '606', name: 'Mr. Kalpesh Naraynrao Banai', amount: 0, status: 'PENDING' as const },
  { flat: '607', name: 'Mr. AshuKumar Harshwardhan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '608', name: 'Jannat Damji', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '701', name: 'Mr. Kumar Raj & Mrs. Soni Kumari', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '702', name: 'Mr. Nikhil Ramakant Kerkar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '703', name: 'Mr. Sandeep Kumar', amount: 0, status: 'PENDING' as const },
  { flat: '704', name: 'Mr. Sachin Nivrutti Savakhande', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '705', name: 'Mr. Ram Kumar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '707', name: 'Mr. Narayan Pandurang Dange', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '708', name: 'Mr. Wasim Jamal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '801', name: 'Mr. Sanchet J. Shetty', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '802', name: 'Mr. Suchit Prakash Gangreddiwar', amount: 0, status: 'PENDING' as const },
  { flat: '803', name: 'Ms. Patricia Robert Daniel', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '804', name: 'Mr. Aliakbar Abbas Haghighi', amount: 0, status: 'PENDING' as const },
  { flat: '805', name: 'Mr. Prasad Surya Yadavilli', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '806', name: 'Mr. Rushikesh Deepak Shinde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '807', name: 'Mr. Gaurav Pandey', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '808', name: 'Mrs. Sujata Surendra Hatkar', amount: 0, status: 'PENDING' as const },
  { flat: '901', name: 'Mr. Girish Jitendra Vij', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '902', name: 'Mr. Nikhil Bhosale', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '903', name: 'Mr. Dhanesh Unnithan & Mrs. Surya Kurup', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '904', name: 'Bennett, Coleman & Co. Ltd.', amount: 0, status: 'PENDING' as const },
  { flat: '905', name: 'Mr. Siddhesh Ghoting', amount: 0, status: 'PENDING' as const },
  { flat: '906', name: 'Mr. Mandar Sunil Govalkar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '907', name: 'Ms. Madhurima', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '908', name: 'Miss. Sakina Fatawala', amount: 0, status: 'PENDING' as const },
  { flat: '1001', name: 'Mr. Khan Yasir Ahmed Nasir', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1002', name: 'Bennett, Coleman & Co. Ltd.', amount: 0, status: 'PENDING' as const },
  { flat: '1003', name: 'Mrs. Shabnam Mirkar', amount: 0, status: 'PENDING' as const },
  { flat: '1004', name: 'Mr. Jagtap Sachin Ashok', amount: 0, status: 'PENDING' as const },
  { flat: '1005', name: 'Mr. Vinay Kumar Gupta', amount: 0, status: 'PENDING' as const },
  { flat: '1006', name: 'Raunak Jagdish Uderani', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1007', name: 'Mr. Rajesh Sharma', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1008', name: 'Ms Shilpa Tapiloo', amount: 0, status: 'PENDING' as const },
  { flat: '1101', name: 'Mr. Cedric', amount: 0, status: 'PENDING' as const },
  { flat: '1102', name: 'Mrs. Swati V. Dangde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1103', name: 'Mrs. Shubhada Ashok Gophane', amount: 2000, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1104', name: 'Mr. Shabbir Patrawala', amount: 0, status: 'PENDING' as const },
  { flat: '1105', name: 'Mrs. Deepjyoti Jaryal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1106', name: 'Ansari Farid Abdul Mannan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1107', name: 'Mr. Alfred Suresh O\'Neill', amount: 0, status: 'PENDING' as const },
  { flat: '1108', name: 'Mr. Kiran Ramdas Tajane', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
];

// Exact Real Residents for B Building (96 Flats: Floors 1 to 12)
export const REAL_B_BUILDING_RESIDENTS = [
  // Floor 1
  { flat: '101', name: 'Mr. Naik Preetam Premanand', amount: 0, status: 'PENDING' as const },
  { flat: '102', name: 'Mr. Vikram Kumar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '103', name: 'Mr. Rajeev Pawar', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '104', name: 'Mrs. Sachdev Veena Harish', amount: 0, status: 'PENDING' as const },
  { flat: '105', name: 'Mrs. Joshna V. Nile & Mr. Vaibhav Nile', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '106', name: 'Mrs. Sharma Bhavna', amount: 0, status: 'PENDING' as const },
  { flat: '107', name: 'Mr. Javed Shaikh', amount: 2000, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '108', name: 'Mrs. Belinda sahil Bhatia', amount: 0, status: 'PENDING' as const },

  // Floor 2
  { flat: '201', name: 'Lalita S', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '202', name: 'Mrs. Abrar Sayed', amount: 0, status: 'PENDING' as const },
  { flat: '203', name: 'Ms. Priyanka', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '204', name: 'Mr. Sudhir Shrivastava', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '205', name: 'Mr. Shahebaz Mainuddin Shaikh', amount: 0, status: 'PENDING' as const },
  { flat: '206', name: 'Mr. Krishna Kumar Verma', amount: 0, status: 'PENDING' as const },
  { flat: '207', name: 'Mr. Sahil Monga & Nisha Kumari', amount: 0, status: 'PENDING' as const },
  { flat: '208', name: 'Mr. Sambhaji Jadav', amount: 0, status: 'PENDING' as const },

  // Floor 3
  { flat: '301', name: 'Miss. Deepa Thakur Rao', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '302', name: 'Mr. Russell Nayak', amount: 0, status: 'PENDING' as const },
  { flat: '303', name: 'Mr. Ankush Bobade', amount: 0, status: 'PENDING' as const },
  { flat: '304', name: 'Mr. Saurabh Jaiswal', amount: 0, status: 'PENDING' as const },
  { flat: '305', name: 'Mrs. Neha Ashton Lazarus', amount: 0, status: 'PENDING' as const },
  { flat: '306', name: 'Mr. Abhishek Jeevan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '307', name: 'Mr. Sunil Kumar & Abha Kumar(Rahul Singh)', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '308', name: 'Mr. Moses Mascarenhas', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 4
  { flat: '401', name: 'Mr. Shahebaz Mainuddin Shaikh', amount: 0, status: 'PENDING' as const },
  { flat: '402', name: 'Mr. Vishal Dilipkumar Shende', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '403', name: 'Miss. Anjali Ajgaonkar', amount: 0, status: 'PENDING' as const },
  { flat: '404', name: 'Ms. Maya Ghughe / Pratibha Malik', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '405', name: 'Mr. Santosh shinde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '406', name: 'Mr. Shailesh Namekar', amount: 0, status: 'PENDING' as const },
  { flat: '407', name: 'Mr. Gaurav Pandey', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '408', name: 'Mrs. Gunjandevi Yadav & Mithlesh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 5
  { flat: '501', name: 'Mrs. Arpita Bhattachrjee', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '502', name: 'Ms. Swarna Biswas', amount: 0, status: 'PENDING' as const },
  { flat: '503', name: 'Mr. Vijaya Udhavrao Kolpe', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '504', name: 'Mr. Parag Bujone', amount: 0, status: 'PENDING' as const },
  { flat: '505', name: 'Amoy Ahwah Lee', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '506', name: 'Mr. Shyam Sunder', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '507', name: 'Mr. Digambar Tanaji Giribuwa', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '508', name: 'Mr. Pradeep Dattajirao Desai', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 6
  { flat: '601', name: 'Mrs. Madhu Kaushik', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '602', name: 'Mr. Apurv', amount: 0, status: 'PENDING' as const },
  { flat: '603', name: 'Mr. Jude joseph Dsouza', amount: 0, status: 'PENDING' as const },
  { flat: '604', name: 'Mr. Prabhat Singh & Mallika Singh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '605', name: 'Mr. Hansmukh Morarji', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '606', name: 'Mrs. Anju Gupta', amount: 1501, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '607', name: 'Mr. Rohan Uday Kavde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '608', name: 'Mr. Sambhaji Jadav', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 7
  { flat: '701', name: 'Mrs. Samina Sajid Malik', amount: 0, status: 'PENDING' as const },
  { flat: '702', name: 'Ms. Priyanka patil', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '703', name: 'Mr. Rohit Prachure', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '704', name: 'Ms. Aarti Dalvi', amount: 0, status: 'PENDING' as const },
  { flat: '705', name: 'Mr. Anand Rakesh Tamang', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '706', name: 'Mrs. Tejshree Deshmukh', amount: 0, status: 'PENDING' as const },
  { flat: '707', name: 'Mr. Deepak Dharmaraj', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '708', name: 'Mr. Manish Ranjan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 8
  { flat: '801', name: 'Mr. Shubham Kumar Singh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '802', name: 'Mr. Sachin Singh & Rajbala Devi', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '803', name: 'Mr. Satish Shivram Bhosale', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '804', name: 'Mr. Moin Munir Shaikh Nuzhat', amount: 0, status: 'PENDING' as const },
  { flat: '805', name: 'Mr. Imran Deshmukh', amount: 0, status: 'PENDING' as const },
  { flat: '806', name: 'Mr. Ankush Ramrao Shinde', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '807', name: 'Mr. Ludhani', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '808', name: 'Mr. Mohit', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 9
  { flat: '901', name: 'Mr. Ganesh Jagannath Jagtap', amount: 0, status: 'PENDING' as const },
  { flat: '902', name: 'Mrs. Suprabha Nandi', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '903', name: 'Mrs. Seema Manoj Pallod', amount: 0, status: 'PENDING' as const },
  { flat: '904', name: 'Mr. Amar Wale', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '905', name: 'Mr. Yusuf Ampanwala', amount: 0, status: 'PENDING' as const },
  { flat: '906', name: 'Mr. Rajesh Bapusaheb Khude', amount: 0, status: 'PENDING' as const },
  { flat: '907', name: 'Mr. Atul Ashok Jagtap', amount: 0, status: 'PENDING' as const },
  { flat: '908', name: 'Mrs. Ekta Gaikwad', amount: 0, status: 'PENDING' as const },

  // Floor 10
  { flat: '1001', name: 'Glyniis Aubey', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1002', name: 'Mr. Ramraje Kakde', amount: 0, status: 'PENDING' as const },
  { flat: '1003', name: 'Mrs. Sampada Mohan Nagraj', amount: 0, status: 'PENDING' as const },
  { flat: '1004', name: 'Miss. Rashida Madraswala', amount: 0, status: 'PENDING' as const },
  { flat: '1005', name: 'Mr. Surendra Dubey', amount: 0, status: 'PENDING' as const },
  { flat: '1006', name: 'Mrs. Alka Dubey', amount: 1501, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1007', name: 'Mr. Mayur Vilasrao Jagtap', amount: 0, status: 'PENDING' as const },
  { flat: '1008', name: 'Mr. Rajiv Arora', amount: 0, status: 'PENDING' as const },

  // Floor 11
  { flat: '1101', name: 'Mr. Aryan Pandey', amount: 0, status: 'PENDING' as const },
  { flat: '1102', name: 'Agnelo Norman', amount: 0, status: 'PENDING' as const },
  { flat: '1103', name: 'Mr. Ravindra Dixit & Swagata Dixit', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1104', name: 'Mrs. Sweta Prasad', amount: 0, status: 'PENDING' as const },
  { flat: '1105', name: 'Mr. Hussain', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1106', name: 'Mr. Ramesh Solanki', amount: 0, status: 'PENDING' as const },
  { flat: '1107', name: 'Mrs. Nivedita Maheshwari', amount: 0, status: 'PENDING' as const },
  { flat: '1108', name: 'Mr. Sanjit Shenoy', amount: 0, status: 'PENDING' as const },

  // Floor 12
  { flat: '1201', name: 'Mrs. Priyanka Shah', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1202', name: 'Mr. Deepak Nagdev', amount: 0, status: 'PENDING' as const },
  { flat: '1203', name: 'Mrs. Samina Lokhandwala', amount: 0, status: 'PENDING' as const },
  { flat: '1204', name: 'Mrs. Tina Arun Rohra', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1205', name: 'Mr. Manoj Madhavdas Lakhi', amount: 0, status: 'PENDING' as const },
  { flat: '1206', name: 'Mr. Rayan Barretto', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '1207', name: 'Mr. Rajan Duggal & Monika Sharma', amount: 0, status: 'PENDING' as const },
  { flat: '1208', name: 'Mr. Rishabh kumar', amount: 0, status: 'PENDING' as const },
];



// Exact Real Residents for C Building (48 Flats: Floors 1 to 6)
export const REAL_C_BUILDING_RESIDENTS = [
  // Floor 1
  { flat: '101', name: 'Clinton Fernandes', amount: 0, status: 'PENDING' as const },
  { flat: '102', name: 'Dhanraj Mane', amount: 0, status: 'PENDING' as const },
  { flat: '103', name: 'Samrat Choudhury', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '104', name: 'Saud Shaikh', amount: 0, status: 'PENDING' as const },
  { flat: '105', name: 'Raheal Rathod', amount: 0, status: 'PENDING' as const },
  { flat: '106', name: 'Ms. Veronica Francis', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '107', name: 'Sanmay Jagtap', amount: 0, status: 'PENDING' as const },
  { flat: '108', name: 'Yogita Shirdhankar', amount: 0, status: 'PENDING' as const },

  // Floor 2
  { flat: '201', name: 'Imrankhan Pathan', amount: 0, status: 'PENDING' as const },
  { flat: '202', name: 'Ashley Carrasco', amount: 0, status: 'PENDING' as const },
  { flat: '203', name: 'Garima Rana', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '204', name: 'Sufiyan Tamboli', amount: 0, status: 'PENDING' as const },
  { flat: '205', name: 'Chetan Habib', amount: 0, status: 'PENDING' as const },
  { flat: '206', name: 'Shriniketan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '207', name: 'Nishad Mohandas', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '208', name: 'Madhu Verma', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 3
  { flat: '301', name: 'Sameer Kaulagekar', amount: 0, status: 'PENDING' as const },
  { flat: '302', name: 'Amol Sathe', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '303', name: 'Sunil Agrawal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '304', name: 'Nitesh A', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '305', name: 'Abid S', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '306', name: 'Mr. Rohan Kotkar', amount: 0, status: 'PENDING' as const },
  { flat: '307', name: 'Rajesh Sapkal', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '308', name: 'Aamay Arora', amount: 0, status: 'PENDING' as const },

  // Floor 4
  { flat: '401', name: 'Kaustubh', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '402', name: 'Rohan Veer', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '403', name: 'Anosh', amount: 0, status: 'PENDING' as const },
  { flat: '404', name: 'Sameer Perampalli', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '405', name: 'Rahul Khade', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '406', name: 'Noel Paul', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '407', name: 'Parikshit Dharmale', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '408', name: 'Aniket', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 5
  { flat: '501', name: 'Anirudh Dipak Fulzele', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '502', name: 'Sandhya Gaikwad', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '503', name: 'Rachel', amount: 0, status: 'PENDING' as const },
  { flat: '504', name: 'Santanu Gauratra', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '505', name: 'Vivek Chavan', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '506', name: 'Hussain', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '507', name: 'Satish Shetty', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '508', name: 'Surajit Das', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },

  // Floor 6
  { flat: '601', name: 'Amber', amount: 0, status: 'PENDING' as const },
  { flat: '602', name: 'Naveen Gupta', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '603', name: 'Param N', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '604', name: 'Hasina S', amount: 0, status: 'PENDING' as const },
  { flat: '605', name: 'Tasneem Palodawala', amount: 0, status: 'PENDING' as const },
  { flat: '606', name: 'Vivek Rahate', amount: 1501, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '607', name: 'Husham', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
  { flat: '608', name: 'Amal Nair', amount: 1500, mode: 'ONLINE' as const, status: 'PAID' as const },
];

export function generateSeedContributions(): Contribution[] {
  const contributions: Contribution[] = [];
  let idCounter = 100;

  // 1. Insert real A Building residents (87 flats)
  REAL_A_BUILDING_RESIDENTS.forEach((item, idx) => {
    idCounter++;
    const isPaid = item.status === 'PAID';
    const expected = 1500;
    const day = (idx % 14) + 15;

    contributions.push({
      id: `contrib-A-${item.flat}`,
      eventId: DEFAULT_EVENT_ID,
      buildingId: 'A',
      flatNumber: `A-${item.flat}`,
      residentName: item.name,
      expectedAmount: expected,
      paidAmount: isPaid ? item.amount : 0,
      paymentMode: item.mode,
      transactionId: isPaid ? `UPI-${Math.floor(10000000 + (idx + 1) * 987654)}` : undefined,
      receiptNumber: isPaid ? `REC-2026-A${item.flat}` : undefined,
      paymentDate: isPaid ? `2026-08-${day < 10 ? '0' + day : day}` : undefined,
      status: item.status,
      remarks: isPaid ? 'Payment received online' : 'Pending follow-up',
      createdAt: '2026-08-01T10:00:00Z',
      updatedAt: '2026-08-30T18:00:00Z',
    });
  });

  // 2. Insert real B Building residents (96 flats)
  REAL_B_BUILDING_RESIDENTS.forEach((item, idx) => {
    idCounter++;
    const isPaid = item.status === 'PAID';
    const expected = 1500;
    const day = (idx % 14) + 15;

    contributions.push({
      id: `contrib-B-${item.flat}`,
      eventId: DEFAULT_EVENT_ID,
      buildingId: 'B',
      flatNumber: `B-${item.flat}`,
      residentName: item.name,
      expectedAmount: expected,
      paidAmount: isPaid ? item.amount : 0,
      paymentMode: item.mode,
      transactionId: isPaid ? `UPI-${Math.floor(20000000 + (idx + 1) * 876543)}` : undefined,
      receiptNumber: isPaid ? `REC-2026-B${item.flat}` : undefined,
      paymentDate: isPaid ? `2026-08-${day < 10 ? '0' + day : day}` : undefined,
      status: item.status,
      remarks: isPaid ? 'Payment received online' : 'Pending follow-up',
      createdAt: '2026-08-01T10:00:00Z',
      updatedAt: '2026-08-30T18:00:00Z',
    });
  });

  // 3. Insert real C Building residents (48 flats)
  REAL_C_BUILDING_RESIDENTS.forEach((item, idx) => {
    idCounter++;
    const isPaid = item.status === 'PAID';
    const expected = 1500;
    const day = (idx % 14) + 15;

    contributions.push({
      id: `contrib-C-${item.flat}`,
      eventId: DEFAULT_EVENT_ID,
      buildingId: 'C',
      flatNumber: `C-${item.flat}`,
      residentName: item.name,
      expectedAmount: expected,
      paidAmount: isPaid ? item.amount : 0,
      paymentMode: item.mode,
      transactionId: isPaid ? `UPI-${Math.floor(30000000 + (idx + 1) * 765432)}` : undefined,
      receiptNumber: isPaid ? `REC-2026-C${item.flat}` : undefined,
      paymentDate: isPaid ? `2026-08-${day < 10 ? '0' + day : day}` : undefined,
      status: item.status,
      remarks: isPaid ? 'Payment received online' : 'Pending follow-up',
      createdAt: '2026-08-01T10:00:00Z',
      updatedAt: '2026-08-30T18:00:00Z',
    });
  });

  return contributions;
}

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: 'prog-1',
    eventId: DEFAULT_EVENT_ID,
    title: 'Ganesh Aagman & Sthapana Ceremony',
    date: '2026-09-14',
    time: '05:00 PM',
    stage: 'Main Entrance & Clubhouse',
    category: 'Ceremony',
    description: 'Grand Ganesh Aagman procession with Dhol Tasha beats followed by traditional Sthapana and 8:00 PM Welcome Aarti.',
    durationMinutes: 180,
    performers: ['Managing Committee', 'Priest Shastri Ji', 'Euriska Dhol Tasha Pathak'],
    order: 1,
    isToday: false,
  },
  {
    id: 'prog-2',
    eventId: DEFAULT_EVENT_ID,
    title: 'Daily Evening Maha Aarti & Prasad',
    date: '2026-09-14',
    time: '08:00 PM',
    stage: 'Clubhouse Temple Podium',
    category: 'Ceremony',
    description: 'Daily community evening aarti and distribution of fresh Modak Prasad every evening from 14 Sep till 25 Sep.',
    durationMinutes: 45,
    performers: ['All Society Families & Prasad Seva Hosts'],
    order: 2,
    isToday: false,
  },
  {
    id: 'prog-3',
    eventId: DEFAULT_EVENT_ID,
    title: 'Kalakriti Cultural Activity Night (Drawing, Skit & Drama)',
    date: '2026-09-19',
    time: '06:00 PM',
    stage: 'Amphitheatre',
    category: 'Drama',
    description: 'Day 1 Cultural Activities: Kids drawing competition, funny society comedy skits, and mimicry acts by resident groups.',
    durationMinutes: 120,
    performers: ['Euriska Little Stars', 'Society Drama Guild', 'Nilesh, Deepak & Group'],
    order: 3,
    isToday: false,
  },
  {
    id: 'prog-4',
    eventId: DEFAULT_EVENT_ID,
    title: 'Cultural Stage Extravaganza (Dance, Singing & Fashion Show)',
    date: '2026-09-20',
    time: '06:30 PM',
    stage: 'Main Stage',
    category: 'Dance',
    description: 'Day 2 Cultural Activities: Kids folk dance, classical Lavani & Gondhal, solo/duet singing, and family fashion showcase.',
    durationMinutes: 150,
    performers: ['Women Cultural Troupe (A & B Wing)', 'Euriska Symphony Band', 'Kids Dance Crew'],
    order: 4,
    isToday: false,
  },
  {
    id: 'prog-5',
    eventId: DEFAULT_EVENT_ID,
    title: 'Community Grand Maha Prasad Dinner',
    date: '2026-09-24',
    time: '08:30 PM',
    stage: 'Clubhouse Lawn',
    category: 'Feast',
    description: 'Special Pre-Visarjan Aarti at 8:00 PM followed by a grand delicious multi-course feast and dinner starting around 8:30 PM for all residents and guests.',
    durationMinutes: 150,
    performers: ['Royal Caterers', 'Euriska Cultural Committee Volunteers'],
    order: 5,
    isToday: false,
  },
  {
    id: 'prog-6',
    eventId: DEFAULT_EVENT_ID,
    title: 'Ganesh Visarjan Procession & Final Farewell',
    date: '2026-09-25',
    time: '04:00 PM',
    stage: 'Main Ground & Visarjan Route',
    category: 'Ceremony',
    description: 'Grand Anant Chaturdashi Visarjan procession starting at 4:00 PM with Gulal, Lezim, Dhol Tasha, and concluding with final Maha Aarti.',
    durationMinutes: 240,
    performers: ['Entire Euriska Society Community', 'Dhol Tasha Troupe'],
    order: 6,
    isToday: false,
  },
  // Festival Calendar 2026-2027
  {
    id: 'festival-1',
    eventId: DEFAULT_EVENT_ID,
    title: 'Sharad Navratri 2026 - Begins',
    date: '2026-10-11',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Sharad Navratri festival begins. A 9-day celebration honoring the divine feminine energy. Vijayadashami (Dussehra) concludes the festival on October 20.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 7,
  },
  {
    id: 'festival-2',
    eventId: DEFAULT_EVENT_ID,
    title: 'Vijayadashami (Dussehra) 2026',
    date: '2026-10-20',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Concludes the 9-day Sharad Navratri celebration. Vijayadashami marks the victory of good over evil and the triumph of Lord Rama over Ravana.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 8,
  },
  {
    id: 'festival-3',
    eventId: DEFAULT_EVENT_ID,
    title: 'Diwali 2026 - Festival of Lights',
    date: '2026-11-08',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Diwali 2026 - The festival of lights celebrating the victory of light over darkness and good over evil. A time for family gatherings, celebrations, and joy.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 9,
  },
  {
    id: 'festival-4',
    eventId: DEFAULT_EVENT_ID,
    title: 'Holi 2027 - Festival of Colors',
    date: '2027-03-22',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Holi 2027 - The festival of colors celebrating spring and new beginnings. Holika Dahan, the bonfire ritual, takes place on March 21, 2027.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 10,
  },
  {
    id: 'festival-5',
    eventId: DEFAULT_EVENT_ID,
    title: 'Holika Dahan 2027',
    date: '2027-03-21',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Holika Dahan - Traditional bonfire ritual marking the eve of Holi. A symbolic representation of burning evil and purification.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 11,
  },
  {
    id: 'festival-6',
    eventId: DEFAULT_EVENT_ID,
    title: 'Eid al-Fitr 2027',
    date: '2027-03-10',
    time: '12:00 PM',
    stage: 'Community Calendar',
    category: 'Ceremony',
    description: 'Eid al-Fitr 2027 - The festival marking the end of Ramadan. A day of celebration, feasting, and community gatherings with joy and blessings.',
    durationMinutes: 1440,
    performers: ['Society Community', 'All Residents'],
    order: 12,
  },
];

export const INITIAL_PERFORMANCES: Performance[] = [
  {
    id: 'perf-1',
    eventId: DEFAULT_EVENT_ID,
    title: 'Kids Traditional Folk Dance',
    performer: 'Euriska Kids Group',
    groupName: 'Euriska Little Stars',
    category: 'Kids Special',
    description: 'Energetic regional folk dance blending Rajasthani Ghoomar and Gujarati Garba with synchronized beats.',
    time: '06:30 PM • Main Stage',
    stage: 'Main Stage',
    imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    relatedProgramId: 'prog-2',
    status: 'SCHEDULED',
  },
  {
    id: 'perf-2',
    eventId: DEFAULT_EVENT_ID,
    title: 'Lavani & Gondhal Cultural Showcase',
    performer: 'Euriska Stree Shakti Group',
    groupName: 'Wings A & B Ensemble',
    category: 'Traditional Dance',
    description: 'A vibrant presentation celebrating the rich heritage of Maharashtra with authentic costume and rhythm.',
    time: '07:15 PM • Main Stage',
    stage: 'Main Stage',
    imageUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=800&q=80',
    ],
    relatedProgramId: 'prog-3',
    status: 'SCHEDULED',
  },
  {
    id: 'perf-3',
    eventId: DEFAULT_EVENT_ID,
    title: 'Comedy Play: "Society Meeting Express"',
    performer: 'Nilesh, Deepak, Sanjay & Group',
    groupName: 'Euriska Theatre Guild',
    category: 'Drama/Skit',
    description: 'A hilarious 30-minute satire on parking slots, AGM debates, and Whatsapp group debates.',
    time: '08:00 PM • Amphitheatre',
    stage: 'Amphitheatre',
    imageUrl: 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=800&q=80',
    relatedProgramId: 'prog-4',
    status: 'SCHEDULED',
  },
  {
    id: 'perf-4',
    eventId: DEFAULT_EVENT_ID,
    title: 'Live Acoustic & Fusion Jam',
    performer: 'Rohan Mehta & The Society Beats',
    groupName: 'Youth Music Club',
    category: 'Vocal Music',
    description: 'Soulful Bollywood retro classics to high-energy pop fusion on guitars, keyboards, and dholak.',
    time: '08:45 PM • Main Stage',
    stage: 'Main Stage',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    relatedProgramId: 'prog-5',
    status: 'SCHEDULED',
  },
];

export const INITIAL_ALBUMS: GalleryAlbum[] = [
  {
    id: 'album-1',
    eventId: DEFAULT_EVENT_ID,
    name: 'Cultural Festival 2026',
    coverImageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
    itemCount: 8,
    date: '2026-08-30',
  },
  {
    id: 'album-2',
    eventId: DEFAULT_EVENT_ID,
    name: 'Ganesh Utsav & Pooja',
    coverImageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=600&q=80',
    itemCount: 6,
    date: '2026-08-28',
  },
  {
    id: 'album-3',
    eventId: DEFAULT_EVENT_ID,
    name: 'Kids Dance Rehearsals',
    coverImageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80',
    itemCount: 5,
    date: '2026-08-25',
  },
];

export const INITIAL_GALLERY_IMAGES: GalleryImage[] = [
  {
    id: 'img-1',
    eventId: DEFAULT_EVENT_ID,
    albumId: 'album-1',
    title: 'Grand Stage Lighting & Floral Mandap',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80',
    category: 'Stage',
    uploadedAt: '2026-08-30T10:00:00Z',
    caption: 'Stage decoration completed by Raj Decorators.',
    likes: 42,
  },
  {
    id: 'img-2',
    eventId: DEFAULT_EVENT_ID,
    albumId: 'album-1',
    title: 'Kids Dance Group in Traditional Attire',
    imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1000&q=80',
    category: 'Kids',
    uploadedAt: '2026-08-30T11:30:00Z',
    caption: 'Ready for the evening performance on Main Stage!',
    likes: 68,
  },
  {
    id: 'img-3',
    eventId: DEFAULT_EVENT_ID,
    albumId: 'album-1',
    title: 'Society Women Folk Dance Troop',
    imageUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1000&q=80',
    category: 'Dance',
    uploadedAt: '2026-08-30T12:15:00Z',
    caption: 'Lavani & Lezim rehearsal team.',
    likes: 54,
  },
  {
    id: 'img-4',
    eventId: DEFAULT_EVENT_ID,
    albumId: 'album-1',
    title: 'Clubhouse Lighting & Rangoli Art',
    imageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1000&q=80',
    category: 'Decoration',
    uploadedAt: '2026-08-30T13:00:00Z',
    caption: 'Eco-friendly floral rangoli by Wing C team.',
    likes: 39,
  },
  {
    id: 'img-5',
    eventId: DEFAULT_EVENT_ID,
    albumId: 'album-1',
    title: 'Live Band Rehearsal Jam',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80',
    category: 'Music',
    uploadedAt: '2026-08-30T14:20:00Z',
    caption: 'Sound check in progress with the Euriska Band.',
    likes: 47,
  },
  {
    id: 'img-6',
    eventId: DEFAULT_EVENT_ID,
    albumId: 'album-1',
    title: 'Evening Crowd & Community Gathering',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80',
    category: 'Audience',
    uploadedAt: '2026-08-30T15:00:00Z',
    caption: 'Residents gathering at the podium lawn.',
    likes: 81,
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-dhol-pathak-01',
    eventId: DEFAULT_EVENT_ID,
    category: 'Ganesh Chaturthi' as any,
    vendor: 'Dhol Pathak',
    description: 'Adv booking',
    amount: 5000,
    paymentMode: 'ONLINE',
    status: 'APPROVED',
    expenseDate: '2026-09-01',
    invoiceNumber: 'ADV-DP-2026-01',
    createdBy: 'Sachin Singh',
    approvedBy: 'Sachin Singh',
    approvedAt: '2026-09-01T10:00:00Z',
    remarks: 'Adv booking for Ganesh Chaturthi',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
];

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: 'spon-1',
    eventId: DEFAULT_EVENT_ID,
    name: 'Majestique Landmarks',
    tier: 'Title',
    amount: 100000,
    logoUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=300&q=80',
    paymentStatus: 'PAID',
    contactPerson: 'Karan Malhotra',
    contactPhone: '+91 98230 11223',
    website: 'https://majestiqueproperties.com',
    description: 'Official Title Sponsor of Euriska Cultural Festival 2026',
  },
  {
    id: 'spon-2',
    eventId: DEFAULT_EVENT_ID,
    name: 'HDFC Home Loans',
    tier: 'Gold',
    amount: 50000,
    logoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=300&q=80',
    paymentStatus: 'PAID',
    contactPerson: 'Megha Nair',
    contactPhone: '+91 98221 44556',
    website: 'https://hdfcbank.com',
    description: 'Banking & Financial Partner',
  },
  {
    id: 'spon-3',
    eventId: DEFAULT_EVENT_ID,
    name: 'Apollo Pharmacy & Clinic',
    tier: 'Silver',
    amount: 25000,
    logoUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
    paymentStatus: 'PAID',
    contactPerson: 'Dr. Vivek Joshi',
    contactPhone: '+91 98900 77889',
    website: 'https://apollopharmacy.in',
    description: 'First Aid & Health Wellness Partner',
  },
  {
    id: 'spon-4',
    eventId: DEFAULT_EVENT_ID,
    name: 'Kalyan Jewellers Kharadi',
    tier: 'Bronze',
    amount: 15000,
    logoUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=300&q=80',
    paymentStatus: 'PAID',
    contactPerson: 'Rajesh Verma',
    contactPhone: '+91 98765 43210',
    website: 'https://kalyanjewellers.net',
    description: 'Gift & Trophy Partner',
  },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-1',
    eventId: DEFAULT_EVENT_ID,
    name: 'Rajesh Sharma',
    role: 'Stage & Artist Coordination',
    buildingId: 'A',
    flatNumber: 'A-203',
    phone: '+91 98231 10022',
    shiftTime: '05:30 PM – 10:00 PM',
    status: 'ON_DUTY',
    tasksCount: 3,
  },
  {
    id: 'vol-2',
    eventId: DEFAULT_EVENT_ID,
    name: 'Pooja Kulkarni',
    role: 'Food & Dinner Counter Management',
    buildingId: 'A',
    flatNumber: 'A-402',
    phone: '+91 98224 55112',
    shiftTime: '07:30 PM – 10:30 PM',
    status: 'ASSIGNED',
    tasksCount: 2,
  },
  {
    id: 'vol-3',
    eventId: DEFAULT_EVENT_ID,
    name: 'Rahul Deshmukh',
    role: 'Sound & Audio-Visual Support',
    buildingId: 'B',
    flatNumber: 'B-301',
    phone: '+91 98901 88334',
    shiftTime: '05:00 PM – 09:30 PM',
    status: 'ON_DUTY',
    tasksCount: 4,
  },
  {
    id: 'vol-4',
    eventId: DEFAULT_EVENT_ID,
    name: 'Sneha Patil',
    role: 'Kids Troupe & Green Room Lead',
    buildingId: 'C',
    flatNumber: 'C-504',
    phone: '+91 98812 77443',
    shiftTime: '05:30 PM – 08:30 PM',
    status: 'ASSIGNED',
    tasksCount: 2,
  },
  {
    id: 'vol-5',
    eventId: DEFAULT_EVENT_ID,
    name: 'Deepak More',
    role: 'Parking & Security Liaison',
    buildingId: 'B',
    flatNumber: 'B-104',
    phone: '+91 98600 33221',
    shiftTime: '06:00 PM – 10:30 PM',
    status: 'ASSIGNED',
    tasksCount: 1,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    eventId: DEFAULT_EVENT_ID,
    title: 'Sound check and microphone testing on Main Stage',
    assignedTo: 'Rahul Deshmukh',
    volunteerId: 'vol-3',
    dueDate: '2026-08-30',
    priority: 'HIGH',
    status: 'COMPLETED',
    category: 'Stage',
    description: 'Verify 6 wireless mics, podium mic, and backup battery packs.',
  },
  {
    id: 'task-2',
    eventId: DEFAULT_EVENT_ID,
    title: 'Green room setup & water dispensers for kid dancers',
    assignedTo: 'Sneha Patil',
    volunteerId: 'vol-4',
    dueDate: '2026-08-30',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    category: 'Backstage',
    description: 'Place 50 costumes, mirrors, and changing partitions.',
  },
  {
    id: 'task-3',
    eventId: DEFAULT_EVENT_ID,
    title: 'Verify buffet counter queue barricades & sanitizer stations',
    assignedTo: 'Pooja Kulkarni',
    volunteerId: 'vol-2',
    dueDate: '2026-08-30',
    priority: 'MEDIUM',
    status: 'TODO',
    category: 'Catering',
    description: 'Coordinate with Royal Caterers team for seamless resident queue.',
  },
  {
    id: 'task-4',
    eventId: DEFAULT_EVENT_ID,
    title: 'Distribute VIP badges & welcome gifts to Sponsors',
    assignedTo: 'Rajesh Sharma',
    volunteerId: 'vol-1',
    dueDate: '2026-08-30',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    category: 'Guests',
    description: 'Welcome Majestique Landmarks and HDFC representatives.',
  },
  {
    id: 'task-5',
    eventId: DEFAULT_EVENT_ID,
    title: 'Collect pending contributions from Wing B 4th & 5th floor',
    assignedTo: 'Deepak More',
    volunteerId: 'vol-5',
    dueDate: '2026-08-30',
    priority: 'LOW',
    status: 'TODO',
    category: 'Finance',
    description: 'Hand over receipts directly to residents.',
  },
];

export const INITIAL_MAHA_PRASAD_RSVPS: MahaPrasadRSVP[] = [
  {
    id: 'rsvp-A-101',
    buildingId: 'A',
    flatNumber: 'A-101',
    residentName: 'Mr. Sujit Sadanand Gokhale',
    phone: '9822011223',
    adultsCount: 3,
    childrenCount: 1,
    totalHeadcount: 4,
    dietaryPreference: 'REGULAR',
    timeSlot: '8:00 PM - 9:00 PM',
    isVolunteering: true,
    notes: 'Will help in queue coordination',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'rsvp-A-201',
    buildingId: 'A',
    flatNumber: 'A-201',
    residentName: 'Mr. Gaurav Chawla',
    phone: '9822044556',
    adultsCount: 2,
    childrenCount: 1,
    totalHeadcount: 3,
    dietaryPreference: 'REGULAR',
    timeSlot: '8:00 PM - 9:00 PM',
    isVolunteering: false,
    notes: '',
    createdAt: '2026-08-21T11:30:00Z',
    updatedAt: '2026-08-21T11:30:00Z',
  },
  {
    id: 'rsvp-A-304',
    buildingId: 'A',
    flatNumber: 'A-304',
    residentName: 'Mr. Vinit Sharma',
    phone: '9822077889',
    adultsCount: 4,
    childrenCount: 0,
    totalHeadcount: 4,
    dietaryPreference: 'JAIN',
    timeSlot: '8:00 PM - 9:00 PM',
    isVolunteering: true,
    notes: 'Jain food requested for 4 members',
    createdAt: '2026-08-22T09:15:00Z',
    updatedAt: '2026-08-22T09:15:00Z',
  },
  {
    id: 'rsvp-B-102',
    buildingId: 'B',
    flatNumber: 'B-102',
    residentName: 'Mr. Mahesh Patil',
    phone: '9890123456',
    adultsCount: 2,
    childrenCount: 2,
    totalHeadcount: 4,
    dietaryPreference: 'REGULAR',
    timeSlot: '9:00 PM - 10:00 PM',
    isVolunteering: true,
    notes: 'Ready for Prasad serving',
    createdAt: '2026-08-22T14:20:00Z',
    updatedAt: '2026-08-22T14:20:00Z',
  },
  {
    id: 'rsvp-B-305',
    buildingId: 'B',
    flatNumber: 'B-305',
    residentName: 'Mrs. Rekha Deshmukh',
    phone: '9890987654',
    adultsCount: 3,
    childrenCount: 0,
    totalHeadcount: 3,
    dietaryPreference: 'REGULAR',
    timeSlot: '8:00 PM - 9:00 PM',
    isVolunteering: false,
    notes: '',
    createdAt: '2026-08-23T16:45:00Z',
    updatedAt: '2026-08-23T16:45:00Z',
  },
  {
    id: 'rsvp-C-202',
    buildingId: 'C',
    flatNumber: 'C-202',
    residentName: 'Mr. Sachin Kulkarni',
    phone: '9765432100',
    adultsCount: 2,
    childrenCount: 1,
    totalHeadcount: 3,
    dietaryPreference: 'REGULAR',
    timeSlot: '9:00 PM - 10:00 PM',
    isVolunteering: true,
    notes: 'Will assist senior citizens',
    createdAt: '2026-08-24T18:00:00Z',
    updatedAt: '2026-08-24T18:00:00Z',
  },
];

